version: "3.9" 
services:
  backend:
    build: backend
    ports:
      - "5001:5001"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "fakePassw0rd"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 
  frontend:
    build: frontend
    ports:
      - "8080:8080" 
    depends_on:
        - backend

        
volumes:
  logvolume01: {}